events {}

http {
    client_max_body_size 500M;
    server {
        listen 80;

        # 1. Normal traffic ko Frontend par bhejo
        location / {
            proxy_pass http://frontend:4200;
            proxy_set_header Host localhost;
        }

        # 2. API traffic ko Backend par bhejo
        location /api/ {
            # Ye line '/api/upload' ko '/upload' banakar backend ko degi
            proxy_pass http://api:3000;
            proxy_set_header Host localhost;
        }
    }
}